# Generated by Django 3.1.2 on 2020-11-09 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0002_auto_20201109_1422'),
    ]

    operations = [
        migrations.AlterField(
            model_name='focusususer',
            name='username',
            field=models.CharField(default='focusususer', max_length=30, unique=True),
        ),
    ]
