# Generated by Django 3.1.2 on 2020-10-19 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0002_auto_20201018_2303'),
    ]

    operations = [
        migrations.AddField(
            model_name='focusususer',
            name='username',
            field=models.CharField(default='focusususer', max_length=30),
        ),
    ]
