# Generated by Django 3.1.2 on 2020-11-19 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20201119_1745'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogfield',
            name='display_image',
            field=models.ImageField(null=True, upload_to='pics'),
        ),
    ]
