# Generated by Django 3.1.2 on 2020-11-19 12:45

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_blogfield_display_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogfield',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
