# Generated by Django 3.1.2 on 2020-11-19 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20201119_1830'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogfield',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
