# Generated by Django 3.1.2 on 2020-11-25 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20201125_2237'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogcomment',
            old_name='post',
            new_name='CommentPost',
        ),
        migrations.RenameField(
            model_name='blogcomment',
            old_name='comment',
            new_name='content',
        ),
    ]
