# Generated by Django 3.1.2 on 2020-11-26 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_blogcomment_object_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogcomment',
            name='object_id',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
