# Generated by Django 3.1.2 on 2020-11-26 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_auto_20201126_1521'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogcomment',
            name='object_id',
        ),
    ]
