# Generated by Django 3.1.2 on 2020-10-16 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_remove_homedata_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='homeurl',
            old_name='name',
            new_name='title',
        ),
    ]
