# Generated by Django 3.1.2 on 2020-10-16 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0003_auto_20201016_1422'),
    ]

    operations = [
        migrations.AddField(
            model_name='homeurl',
            name='img',
            field=models.ImageField(null=True, upload_to='pics'),
        ),
    ]
