# Generated by Django 3.1.2 on 2020-10-16 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0004_homeurl_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homeurl',
            name='img',
            field=models.ImageField(upload_to='pics'),
        ),
    ]
