# Generated by Django 3.1.2 on 2020-10-17 06:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='VideoContents',
            new_name='VideoContent',
        ),
    ]
