# Generated by Django 3.1.2 on 2020-10-17 06:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0002_auto_20201017_1205'),
    ]

    operations = [
        migrations.AddField(
            model_name='videocontent',
            name='datetime',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
