# Generated by Django 3.1.2 on 2020-10-17 06:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0003_videocontent_datetime'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videocontent',
            name='datetime',
        ),
        migrations.AddField(
            model_name='videocontent',
            name='CurrentDateTime',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 17, 12, 19, 37, 473454)),
        ),
    ]
