# Generated by Django 3.1.2 on 2020-10-17 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0004_auto_20201017_1219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videocontent',
            name='CurrentDateTime',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
