# Generated by Django 3.1.2 on 2020-10-17 06:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0005_auto_20201017_1226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videocontent',
            name='CurrentDateTime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
