# Generated by Django 3.1.2 on 2020-10-17 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0006_auto_20201017_1244'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='videocontent',
            options={'ordering': ['CurrentDateTime']},
        ),
    ]
