# Generated by Django 3.1.2 on 2020-10-18 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0007_auto_20201017_1259'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='videocontent',
            options={'ordering': ['-CurrentDateTime']},
        ),
    ]
