# Generated by Django 3.1.2 on 2020-11-21 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0010_auto_20201106_2055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videocontent',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
